# Generated by Django 4.1.7 on 2023-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='county',
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
