# Generated by Django 4.1.7 on 2023-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0004_rename_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
    ]
